### ISSUE TITLE
Docker Hub & WPF

### ISSUE THREAD

**Issue by danipalli** [htl-perg-2019-20-5ahif/docker-wpf-exercise-danipalli#1]
Dear Mr. Stropek,

This is the URL for the image on Docker Hub:
https://hub.docker.com/r/danipalli/carbookingapi

I also finished the WPF Client.

Kind regards
Daniel Pallinger

**Comment by rstropek** [comment]
Just FYI: By putting the Dockerfile in the solution folder, all files below this folder will be transferred as the *build context* to the Docker host. In your case, this includes (unnecessarily) the WPF client. [Read more](https://medium.com/better-programming/docker-tips-about-the-build-context-dbc76505e178) about how you can optimize *docker build* using *.dockerignore* if you are interested.

Greetings,
Rainer Stropek.
